language: java
sudo: false
jdk:
  - oraclejdk8

script:
  - ./gradlew build

after_success:
  - pwd
  - cp -R "$TRAVIS_BUILD_DIR/workshop/build/docker/docs/" "$TRAVIS_BUILD_DIR"
  - git init
  - git config user.name "Travis CI"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
