language: java
sudo: false
jdk:
  - oraclejdk8

script:
  - ./gradlew build

after_success:
  - cd "$TRAVIS_BUILD_DIR/workshop/build/docker/docs/"
  - pwd
  - ls
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - git status
  - git add .
  - git status
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
