= Additional assignments
The following assignments are extra. They give less information upfront and you'll have to investigate a bit yourself.

== Run a Selenium Hub with nodes for Firefox and Chrome
In the previous assignment we used a single Firefox container, but often you will want to test your application in multiple browsers.
Figure out which https://github.com/SeleniumHQ/docker-selenium[containers, window="_blank"] you need and how to adjust the SimpleTest class to use the Chrome browser.

== Docker Compose
Let's see if we can do the previous assignment again, using https://docs.docker.com/compose/[Docker Compose, window="_blank"]. Create a YAML file that describes the necessary containers and bring them online with the `docker-compose` command.

    Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration.

