== Building images
*Running pre-made images is a lot of fun and can save you a lot of time, but at some point you will want to create your own images.*

The training/webapp image is limited in that it can only say "Hello World" or "Hello Your Name", lets see if we can expand on the original image to connect to a Postgres database and display the name stored there.

=== What do we need to change?
In order to add the ability to connect to a database we have to change a number of things:

. Expand the original image
.. Add Python dependencies to enable connections to a Postgres database to the image
.. Replace the original Python application with our version inside the Docker image
. Run a database with data
.. Run a Postgres database image
.. Add our message to the running database
. Run the newly build image
.. Look at the message from the database through the website

The following sections will discuss all these steps one-by-one.

==== Changes to the image
In order to build a Docker image yourself you need a https://docs.docker.com/engine/reference/builder/[Dockerfile]. In this case we will supply you with the Dockerfile necessary to create the image. But you will have to run the build process yourself to make the image available to your Docker daemon.

. Go to docker-images/training-webapp-postgres folder
. Review the Dockerfile to understand what we are building

 FROM training/webapp
 RUN apt-get -y update && apt-get -y install libpq-dev python-dev
 RUN pip install pygresql
 ADD app.py /opt/webapp/app.py

.. We use the training/webapp image as a base-image
.. We run 2 commands inside the container to add the Python dependencies
.. We overwrite the existing app.py file with our new app.py file that will check the database.

==== Building the new image
We now have to instruct Docker to pickup the Dockerfile and build it with the tag "testnetapp".

.Build the new image with a tag
 docker build -t testnetapp .

NOTE: Make sure your working directory is docker-images/training-webapp-postgres

==== Starting the new image
Before we start a container with the testnetapp image we first need to start a Postgres database that will store the message for us.

Luckily, we can use an off-the-shelve image provided by https://hub.docker.com/_/postgres/[Postgres].

.Run the Postgres image with a variable to set the password
----
docker run --name pg -e POSTGRES_PASSWORD=testnet -d postgres
----

.Connect with PSQL to the database
 docker run -it --rm --link pg:pg postgres psql -h pg -U postgres

.Execute commands in the running database to prepare data

 CREATE DATABASE testnet;
 \c testnet
 CREATE TABLE kv (key varchar(100) PRIMARY KEY, value varchar(100));
 INSERT INTO kv VALUES ('provider','testnet on pg');
 SELECT * FROM kv; -- Check that the data is really there
 \q

.Now run the app and check that your message is there
 docker run -ti --link pg:pg -p 5000:5000 testnetapp
