= Building images
*Running pre-made images is very useful and can save you a lot of time, but at some point you will want to create your own images.*

The `training/webapp` image is limited in that it can only say "Hello World" or "Hello Your Name", let's see if we can expand on the original image to display a value stored in a Postgres database.

== What do we need to change?
In order to add the ability to connect to a database we have to change a number of things:

. Expand the original image
.. Add Python dependencies to enable connections to a Postgres database
.. Replace the original Python application with our version
. Run a database with data
.. Run a Postgres database image
.. Add our data to the running database
. Run the newly built image
.. Display the data from the database on the webpage

The following sections will discuss all these steps one-by-one.

=== Changes to the image
In order to build a Docker image yourself you need a https://docs.docker.com/engine/reference/builder/[Dockerfile]. In this case we will supply you with the Dockerfile necessary to create the image. But you will have to run the build process yourself to make the image available to your Docker daemon.

. Go to `docker-images/training-webapp-postgres` folder
. Review the Dockerfile to understand what we are building

 [a] FROM training/webapp
 [b] RUN apt-get -y update && apt-get -y install libpq-dev python-dev
 [b] RUN pip install pygresql
 [c] ADD app.py /opt/webapp/app.py

.. We use the `training/webapp` image as a base-image
.. We run 2 commands inside the container to add the Python dependencies
.. We overwrite the existing `app.py` file with our new `app.py` file that will check the database.

=== Building the new image
We now have to instruct Docker to pickup the Dockerfile and build it with the tag `testnetapp`.

NOTE: Make sure your working directory is `docker-images/training-webapp-postgres`

.Build the new image with a tag
 docker build -t testnetapp .

==== Starting the new image
Before we start a container with the `testnetapp` image we first need to start a Postgres database that will store our data for us.

Luckily, we can use an off-the-shelf image provided by https://hub.docker.com/_/postgres/[Postgres].

.Run the Postgres image with a variable to set the password
----
docker run --name pg -e POSTGRES_PASSWORD=testnet -d postgres
----
==== Add data to the database
====
Because you may not have a Postgres database client installed we start another container from the Postgres image to connect to the previously started container. From there we can add some data to the database to display in the testnetapp.

.Connect with PSQL to the database
 docker run -it --rm --link pg:pg postgres psql -h pg -U postgres

.Execute commands in the running database to prepare data
 CREATE DATABASE testnet;
 \c testnet
 CREATE TABLE kv (key varchar(100) PRIMARY KEY, value varchar(100));
 INSERT INTO kv VALUES ('provider','testnet on pg');
 SELECT * FROM kv; -- Check that the data is really there
 \q
====

.Now run the app and check that your data is displayed
 docker run -ti --link pg:pg -p 5000:5000 testnetapp
