= Installation instructions

In order to do this workshop you need to install Docker Desktop on your machine.

== Mac
Please install Docker Community Edition for Mac. You can find the download in https://store.docker.com/editions/community/docker-ce-desktop-mac[the Docker store].

== Windows
Choose the correct Docker installation based on your Windows version.

* Windows 8 or earlier, Windows 10 Home edition
** Install Docker Toolbox from https://docs.docker.com/toolbox/overview/[the Docker website].
* Windows 10 Professional or Enterprise 64-bit
** Install Docker Community Edition for Windows from https://store.docker.com/editions/community/docker-ce-desktop-windows[the Docker store].

== Verify the installation
After the installation is complete, continue with the first exercise to verify that your setup is running correctly.

[NOTE]
*Hardware Virtualization disabled* +
If you encounter the message "VT-x/AMD-v has to be enabled", please enable "Intel Virtualization" in the BIOS of your system. This is required for running virtual machines. Detailed instructions can be found http://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/[here] under "Access the BIOS or UEFI Firmware".

= Reference material

== Presentation
You can find the slides of the presentation on https://docs.google.com/presentation/d/e/2PACX-1vQHlN3M4JyKT7lBUZeredvSw93gUoUhAJBSE2zTyEP9LHqO9AhvOTQIVIWz3op6feL_3rTVYFDDGdvx/pub?start=false&loop=false&delayms=3000[Google Drive].

== Download the zip (optional)
If you like, you can link:{project-name}.zip[download] all the assignments for offline viewing.
